# Generated by Django 5.0.4 on 2026-06-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_presence', '0006_remove_cours_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='modules',
        ),
    ]
