# Generated by Django 5.0.4 on 2026-06-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_presence', '0007_remove_etudiant_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarySeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField()),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('est_ouverte', models.BooleanField(default=True)),
                ('token_qr', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('validite_min', models.PositiveIntegerField(default=120)),
                ('salle', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_seances', to='gestion_presence.enseignant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_seances', to='gestion_presence.module')),
            ],
            options={
                'db_table': 'temporary_seances',
                'ordering': ['-date_seance', '-heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_validation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('retard', 'Retard')], default='present', max_length=20)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_presences', to='gestion_presence.etudiant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='gestion_presence.temporaryseance')),
            ],
            options={
                'db_table': 'temporary_presences',
                'ordering': ['-heure_validation'],
                'unique_together': {('etudiant', 'seance')},
            },
        ),
    ]
