# Generated by Django 5.0.4 on 2026-06-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_presence', '0008_temporaryseance_temporarypresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryseance',
            name='qr_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
