# Generated by Django 5.0.4 on 2026-06-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_presence', '0012_rename_licence_niveaux'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['filiere__nom', 'semestre', 'nom']},
        ),
        migrations.RenameField(
            model_name='filiere',
            old_name='formations',
            new_name='semesters',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='semester',
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('nom', 'filiere', 'semestre')},
        ),
        migrations.RemoveField(
            model_name='module',
            name='niveau',
        ),
    ]
