# Generated by Django 5.0.4 on 2026-06-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_presence', '0013_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='device_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarypresence',
            name='device_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='temporaryseance',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporaryseance',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
