# Generated by Django 5.0.4 on 2026-06-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_presence', '0014_presence_device_uuid_qrcode_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='filieres',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='gestion_presence.filiere'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='enseignants', to='gestion_presence.module'),
        ),
    ]
