# Generated by Django 5.0.4 on 2026-07-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_presence', '0016_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='max_distance',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='temporaryseance',
            name='max_distance',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
