# Generated by Django 5.0.4 on 2026-07-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_presence', '0017_seance_max_distance_temporaryseance_max_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'salles',
                'ordering': ['id'],
            },
        ),
    ]
