# Generated by Django 5.0.4 on 2026-07-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_presence', '0019_auto_20260711_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='etudiants', to='gestion_presence.module'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='semestre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
